/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "inverse-primary": "#795a00",
        "tertiary-fixed-dim": "#ebe857",
        "outline": "#6f7588",
        "on-secondary-container": "#fff7e7",
        "error-dim": "#d53d18",
        "primary-container": "#fdc003",
        "error": "#ff7351",
        "secondary-fixed": "#fcd83f",
        "primary-fixed": "#fdc003",
        "on-error": "#450900",
        "surface-container-lowest": "#000000",
        "on-secondary": "#5b4b00",
        "outline-variant": "#424859",
        "on-tertiary-fixed": "#4b4a00",
        "surface-container-low": "#0c1324",
        "surface-dim": "#080e1d",
        "secondary-fixed-dim": "#edca30",
        "on-error-container": "#ffd2c8",
        "surface-container-high": "#171f33",
        "surface-variant": "#1d253b",
        "tertiary-container": "#f4f15e",
        "surface-container-highest": "#1d253b",
        "secondary-dim": "#edca30",
        "inverse-on-surface": "#4f5566",
        "on-tertiary-container": "#5b5a00",
        "tertiary-fixed": "#faf763",
        "on-tertiary-fixed-variant": "#696800",
        "on-surface": "#e0e5fb",
        "on-primary-fixed": "#3d2b00",
        "on-primary-container": "#553e00",
        "surface-tint": "#ffd16c",
        "primary": "#ffd16c",
        "on-surface-variant": "#a5aabf",
        "primary-fixed-dim": "#ecb200",
        "error-container": "#b92902",
        "on-primary-fixed-variant": "#604700",
        "on-secondary-fixed-variant": "#665500",
        "surface-bright": "#222c43",
        "surface": "#080e1d",
        "surface-container": "#12192b",
        "tertiary-dim": "#ebe857",
        "on-primary": "#604700",
        "secondary-container": "#705d00",
        "tertiary": "#fffcc6",
        "primary-dim": "#ecb200",
        "inverse-surface": "#faf8ff",
        "on-tertiary": "#636200",
        "background": "#080e1d",
        "on-secondary-fixed": "#463900",
        "secondary": "#fcd83f",
        "on-background": "#e0e5fb"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "fontFamily": {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      }
    },
  },
  plugins: [],
}